const db = require('../db');
const { MessageFlags } = require('discord.js');
const crypto = require('crypto');

module.exports = async (interaction) => {
    await interaction.deferReply({ flags: MessageFlags.Ephemeral });

    const tier = interaction.options.getString('tier');
    const months = interaction.options.getInteger('months');
    const note = interaction.options.getString('note') || 'Generated by admin';

    // Generate random key (e.g., AK-XXXX-XXXX)
    const randomBuffer = crypto.randomBytes(4);
    const key = `AK-${randomBuffer.toString('hex').toUpperCase()}-${crypto.randomBytes(2).toString('hex').toUpperCase()}`;

    try {
        await db.query(`
            INSERT INTO license_keys (key_id, plan_tier, duration_months, notes)
            VALUES ($1, $2, $3, $4)
        `, [key, tier, months, note]);

        await interaction.editReply({
            content: `✅ **ライセンスキーを生成しました。**\n\n**キー:** \`${key}\`\n**プラン:** ${tier}\n**期間:** ${months}ヶ月\n\nこのキーをユーザーにお伝えください。一度使用されると無効になります。`
        });
    } catch (err) {
        console.error('Error generating key:', err);
        await interaction.editReply({ content: '❌ キーの生成に失敗しました。' });
    }
};
